services:
  speaches:
    extends:
      file: compose.yaml
      service: speaches
    image: ghcr.io/godsquantum/speaches-reloaded:latest-vulkan
    environment:
      TRANSCRIBE_BACKEND: vulkan
      WHISPER__INFERENCE_DEVICE: cpu
      WHISPER__COMPUTE_TYPE: "${WHISPER_COMPUTE_TYPE:-int8}"
      WHISPER__CPU_THREADS: "${WHISPER_CPU_THREADS:-0}"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "${RENDER_GID:-109}"

volumes:
  speaches-models:
